services:
  - type: web
    name: genmem-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-token
      - key: OPENAI_API_KEY
        value: your-openai-key
      - key: REPLICATE_API_TOKEN
        value: your-replicate-key
    build:
      pythonVersion: 3.11.8
