services:
  - type: web
    name: memaigen
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
    build:
      aptPackages:
        - build-essential
        - libffi-dev
        - python3-dev
        - gcc
