services:
  - type: web
    name: genmem-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your-real-telegram-bot-token
      - key: OPENAI_API_KEY
        value: your-real-openai-key
      - key: REPLICATE_API_TOKEN
        value: your-real-replicate-key
